// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKfmzzoZy6JICJzWDBB4s9j3_-s1ipmnk',
    appId: '1:881326841035:web:df81cffcba2799d3cd8f4e',
    messagingSenderId: '881326841035',
    projectId: 'pest-control-b0140',
    authDomain: 'pest-control-b0140.firebaseapp.com',
    storageBucket: 'pest-control-b0140.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWkYLbVthEoWvT3IqMMM6Jj3321YQ4wbo',
    appId: '1:622260458070:android:705e943f08b7ac6a9261f7',
    messagingSenderId: '622260458070',
    projectId: 'el-talk',
    storageBucket: 'el-talk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4cgBSpEMcLpU_HkZTgH5wKT99nbuHeyg',
    appId: '1:622260458070:ios:890c67d4a465625a9261f7',
    messagingSenderId: '622260458070',
    projectId: 'el-talk',
    storageBucket: 'el-talk.appspot.com',
    androidClientId: '622260458070-6aom33u3vaf7dpn4hc2svhc9c6m1aoao.apps.googleusercontent.com',
    iosClientId: '622260458070-rd6rjdku4ahkuqku4nbj1f1ldfi5nkcm.apps.googleusercontent.com',
    iosBundleId: 'ng.com.obkm.adminDashboard',
  );
}